### ISSUE TITLE
Only use dynamic variables for full paths

### ISSUE THREAD

**Issue by gahjelle** [gahjelle/configaroo#5]
Consider the following TOML-file:

```toml
[log]
level  = "info"
format = "<green>{elapsed}</green> <level>{level:<8} {message}</level>"
```

The `log.format` string contains fields that are used by the logging engine. However, currently the `level:<8` field is replace by `info    ` because `log.level` is replacing `level` as well. This missing scope makes dynamic variables too aggresive.
