### ISSUE TITLE
Allow nested dynamic variables

### ISSUE THREAD

**Issue by gahjelle** [gahjelle/configaroo#6]
Sometimes a dynamic variable may have another dynamic variable nested in its value. For example:

```toml
data_path = "{project_path}/data"
db_file = "{data_path}/sqlite.db"
```

Currently, dynamic variables only resolve to the first level. The configuration above is turned into:

```python
{'data_path': '/home/configaroo/data', 'db_file': '{project_path}/data/sqlite.db'}
```

Here, `db_file` should resolve fully, to `'/home/configaroo/data/sqlite.db'`.
